### ISSUE TITLE
Markdown のバグ

### ISSUE THREAD

**Issue by nakki83** [NatsukiSugawara/magict#30]
```ruby:hoge.rb
とすると

ログ
  Rendered tasks/show.html.erb within layouts/application (19.9ms)
Completed 500 Internal Server Error in 34ms (ActiveRecord: 1.3ms)

ActionView::Template::Error (Invalid id given: ruby:hoge.rb):
    48:
    49:         <h5><%= @task.title %></h5>
    50:         <hr>
    51:         <%= markdown(@task.note) %>
    52:       </div>
    53:     </div>
    54:   </div>
  app/helpers/application_helper.rb:13:in `block_code'
  app/helpers/application_helper.rb:29:in `render'
  app/helpers/application_helper.rb:29:in `markdown'
  app/views/tasks/show.html.erb:51:in `_app_views_tasks_show_html_erb__1376223342699794724_70314893728000'





```
というエラーが発生する

**Comment by nakki83** [comment]
![161222-0001](https://cloud.githubusercontent.com/assets/13149705/21420152/4cc81c2c-c86f-11e6-9045-6be2e34566a0.png)
